---
call: RetrieveEnvironmentInfo
service: ElasticBeanstalk
tests:
  - expected: i-92a3ceff
    op: eq
    path: EnvironmentInfo.0.Ec2InstanceId
  - expected: tail
    op: eq
    path: EnvironmentInfo.0.InfoType
  - expected: https://elasticbeanstalk.us-east-1.s3.amazonaws.com/environments%2Fa514386a-709f-4888-9683-068c38d744b4%2Flogs%2Fi-92a3ceff%2F278756a8-7d83-4bc1-93db-b1763163705a.log?Expires=1291236023%26AuthParams
    op: eq
    path: EnvironmentInfo.0.Message
  - expected: 2010-11-17T20:40:23.210Z
    op: eq
    path: EnvironmentInfo.0.SampleTimestamp
